name: Mirror to GitCode

on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror this repo to GitCode
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/jasonisbrave
          dst: gitcode/jasonisbrave
          dst_token: ${{ secrets.GITCODE_TOKEN }}
          dst_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
          account_type: user
          static_list: "yongge-restaurant-skill"
          force_update: true
          debug: true
